In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 

In [3]:
data = pd.read_csv('DEV_SAMPLE.csv') 

In [4]:
data.head(5)

Cust_ID  Target  Age Gender    Balance Occupation  No_OF_CR_TXNS AGE_BKT  \
0  C16505       0   41      M   91519.92   SELF-EMP             38   41-45   
1  C17241       0   52      M  117288.96        SAL             17     >50   
2  C18802       0   31      F  259827.44       SENP              8   31-35   
3  C19289       0   45      F   26677.55       PROF             14   41-45   
4  C14028       0   39      F   43440.31       SENP              1   36-40   

   SCR  Holding_Period  
0  926              15  
1  768              13  
2  816               5  
3  353              18  
4  751              31

In [26]:
def mapping(data,feature):
    featureMap=dict()
    count=0
    for i in sorted(data[feature].unique(),reverse=True):
        featureMap[i]=count
        count=count+1
    data[feature]=data[feature].map(featureMap)
    return data

In [27]:
data=mapping(data,"Occupation")
data

Cust_ID  Target  Age Gender    Balance  Occupation  No_OF_CR_TXNS  \
0      C16505       0   41      M   91519.92           1             38   
1      C17241       0   52      M  117288.96           2             17   
2      C18802       0   31      F  259827.44           0              8   
3      C19289       0   45      F   26677.55           3             14   
4      C14028       0   39      F   43440.31           0              1   
...       ...     ...  ...    ...        ...         ...            ...   
13995  C19359       0   55      F  406714.26           1             15   
13996   C2811       0   29      M  292974.28           0              6   
13997   C4470       0   30      F  402435.83           0             13   
13998   C8476       0   37      M  105289.81           0              6   
13999  C14747       0   21      F  189101.29           0             16   

      AGE_BKT  SCR  Holding_Period  
0       41-45  926              15  
1         >50  768              13  
2       31-35  816               5  
3       41-45  353              18  
4       36-40  751              31  
...       ...  ...             ...  
13995     >50  668              18  
13996   26-30  626               7  
13997   26-30  540              27  
13998   36-40  319              28  
13999     <25  820              31  

[14000 rows x 10 columns]

In [28]:
x = data.iloc[:, [4, 5]].values  
y = data.iloc[:, 1].values 

In [29]:
x

array([[9.1519920e+04, 1.0000000e+00],
       [1.1728896e+05, 2.0000000e+00],
       [2.5982744e+05, 0.0000000e+00],
       ...,
       [4.0243583e+05, 0.0000000e+00],
       [1.0528981e+05, 0.0000000e+00],
       [1.8910129e+05, 0.0000000e+00]])

In [30]:
y

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [31]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 

In [32]:
from sklearn.model_selection import train_test_split 
xtrain, xtest, ytrain, ytest = train_test_split( 
        x, y, test_size = 0.25, random_state = 0) 

In [33]:
def mapping(data,feature):
    featureMap=dict()
    count=0
    for i in sorted(data[feature].unique(),reverse=True):
        featureMap[i]=count
        count=count+1
    data[feature]=data[feature].map(featureMap)
    return data

In [23]:
data1=mapping(data,"Occupation")

In [24]:
data1

Cust_ID  Target  Age Gender    Balance  Occupation  No_OF_CR_TXNS  \
0      C16505       0   41      M   91519.92           2             38   
1      C17241       0   52      M  117288.96           1             17   
2      C18802       0   31      F  259827.44           3              8   
3      C19289       0   45      F   26677.55           0             14   
4      C14028       0   39      F   43440.31           3              1   
...       ...     ...  ...    ...        ...         ...            ...   
13995  C19359       0   55      F  406714.26           2             15   
13996   C2811       0   29      M  292974.28           3              6   
13997   C4470       0   30      F  402435.83           3             13   
13998   C8476       0   37      M  105289.81           3              6   
13999  C14747       0   21      F  189101.29           3             16   

      AGE_BKT  SCR  Holding_Period  
0       41-45  926              15  
1         >50  768              13  
2       31-35  816               5  
3       41-45  353              18  
4       36-40  751              31  
...       ...  ...             ...  
13995     >50  668              18  
13996   26-30  626               7  
13997   26-30  540              27  
13998   36-40  319              28  
13999     <25  820              31  

[14000 rows x 10 columns]

In [34]:
from sklearn.preprocessing import StandardScaler 
sc_x = StandardScaler() 
xtrain = sc_x.fit_transform(xtrain)  
xtest = sc_x.transform(xtest) 
print (xtrain[0:10, :]) 

[[ 0.46337701 -0.503041  ]
 [ 2.2560092  -0.503041  ]
 [-0.17610695 -1.37321076]
 [-0.66938578  0.36712877]
 [-0.83869009 -0.503041  ]
 [-0.79270006  1.23729853]
 [ 0.50565015 -0.503041  ]
 [ 2.31601989  1.23729853]
 [-0.58977373  1.23729853]
 [-0.01464524  1.23729853]]


In [35]:
from sklearn.linear_model import LogisticRegression 
classifier = LogisticRegression(random_state = 0) 
classifier.fit(xtrain, ytrain) 

C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=0, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [36]:

y_pred = classifier.predict(xtest)

In [37]:
from sklearn.metrics import confusion_matrix 
cm = confusion_matrix(ytest, y_pred) 
  
print ("Confusion Matrix : \n", cm) 

Confusion Matrix : 
 [[3203    0]
 [ 297    0]]


In [38]:
from sklearn.metrics import accuracy_score 
print ("Accuracy : ", accuracy_score(ytest, y_pred)) 


Accuracy :  0.9151428571428571
